{ lib, pkgs, modulesPath, ... }:
{
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./lxd.nix
    # Include the OrbStack-specific configuration.
    ./orbstack.nix
  ];

  users.users.shayne = {
    uid = lib.mkForce 501;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    isNormalUser = lib.mkForce false;
    group = "users";
    createHome = true;
    home = "/home/shayne";
    homeMode = "700";
    useDefaultShell = true;
  };

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Virtualization settings
  virtualisation.docker.enable = true;
  # virtualisation.rosetta.enable = true;

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.mutableUsers = false;

  environment.systemPackages = with pkgs; [
    bindfs
    gnumake
    killall
    niv
    tailscale
    iptables
  ];

  services.qemuGuest.enable = true;
  services.tailscale.enable = true;
}
